default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres

development:
  <<: *default
  database: BaseApp_development

test:
  <<: *default
  database: BaseApp_test
  
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
